Augi
amarshall45676/cdb-frontend pull request #1
Opened 2018-06-28 01:05 UTC by adliebster

I have added an array in the partner.component.ts file which holds the name, phone number, email, title, and affiliated organization of the point of contact the CCL has to organizations. In the associated HTML file, I have used an *ngFor to display all of the members of the above mentioned array except for the affiliated organization, which is hidden.

2018-06-28 01:12 UTC, amarshall45676 requested changes
So this is a review of the code you just committed. Take a look at the comments I left, and make the requested changes. Other than these two it LGTM!

2018-06-28 01:12 UTC, amarshall45676 commented on src/app/landing/landing.component.html
> +  </p>
You can remove this.

2018-06-28 01:12 UTC, amarshall45676 commented on src/app/partners/partner/partner.component.html
> +    Partner Name: {{contact.name}}
These should be displayed on different lines try adding a <br> in between lines.

2018-06-28 14:46 UTC, adliebster commented
Ok I made the requested changes and pushed the new code.

2018-06-29 20:05 UTC, amarshall45676 commented on src/app/partners/partner/partner.component.ts
> +    // this.createEntity('contact', this.contactForm).then((entityResult: Object) => {
Try your best to keep commented out code out of the commits. I will be sure to take it out before this is merged though.

2018-06-29 20:05 UTC, amarshall45676 approved these changes
LGTM

2018-06-29 20:05 UTC, merged